name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *" # 매일 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }} # 본인의 깃허브 유저네임
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_out_path_dark: dist/github-contribution-grid-snake-dark.svg
          
          # 여기서 색상을 커스터마이즈 할 수 있습니다
          color_snake: "#43B02A"           # 뱀 색상
          color_dots: "#1D672F,#2F8132,#43B02A,#82C341,#AEE05D"  # 잔디 색상 (낮은 기여도 순)

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
