name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_PATH: "profile-3d-contrib/profile-3d.svg"  # 출력 경로 지정
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: |
            {
              "type": "normal",
              "colors": {
                "levelColors": [
                  "#162932",
                  "#1B3E46",
                  "#1F4B59",
                  "#24586C",
                  "#286580"
                ],
                "backgroundColor": "#ffffff"
              }
            }

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generate 3D Contribution Graph" || exit 0
          git push
